// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq8KZdxP-x_LKQH0JbVriN1y-EAyMyYwU',
    appId: '1:973681969865:web:48fe1c895abfe11ccadb18',
    messagingSenderId: '973681969865',
    projectId: 'ankit-assignment-421e1',
    authDomain: 'ankit-assignment-421e1.firebaseapp.com',
    storageBucket: 'ankit-assignment-421e1.appspot.com',
    measurementId: 'G-LTD9PEFX0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFCHeR_3CRkGAN-0mvnh1N2vVLwOjYDYw',
    appId: '1:973681969865:android:44d2002a7c3bd3cccadb18',
    messagingSenderId: '973681969865',
    projectId: 'ankit-assignment-421e1',
    storageBucket: 'ankit-assignment-421e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOaWqV5IaRK1ZOYofXYJ_9lYCMqZ1-rNE',
    appId: '1:973681969865:ios:70bfa74dd2365d98cadb18',
    messagingSenderId: '973681969865',
    projectId: 'ankit-assignment-421e1',
    storageBucket: 'ankit-assignment-421e1.appspot.com',
    iosBundleId: 'com.example.ankitAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOaWqV5IaRK1ZOYofXYJ_9lYCMqZ1-rNE',
    appId: '1:973681969865:ios:0f2fde2c2b04832fcadb18',
    messagingSenderId: '973681969865',
    projectId: 'ankit-assignment-421e1',
    storageBucket: 'ankit-assignment-421e1.appspot.com',
    iosBundleId: 'com.example.ankitAssignment.RunnerTests',
  );
}
